name: Объявление
description: Новости от автора (лучше писать maintainers)
title: "[Объявление]: "
body:
  - type: textarea
    id: body
    attributes:
      label: Текст объявления
    validations:
      required: true